services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 3000:3000
    networks:
      - app-network
    stop_grace_period: 3s

networks:
  app-network:
